2024-01-04 12:46:04.249994: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-04 12:46:04.517399: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-04 12:46:04.517445: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-01-04 12:46:07.911306: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-04 12:46:07.915666: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-04 12:46:07.915683: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2024-01-04 12:46:15.679360: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-01-04 12:46:15.679613: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (eu-g5-045-4): /proc/driver/nvidia/version does not exist
2024-01-04 12:46:15.681609: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/cluster/apps/nss/python/3.7.4/x86_64/lib64/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/cluster/home/hugifl/.local/lib/python3.7/site-packages/keras/backend.py:452: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  "`tf.keras.backend.set_learning_phase` is deprecated and "
/cluster/home/hugifl/scim/scim/trainer.py:148: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  adata.obsm['code'] = code.numpy()
/cluster/home/hugifl/.local/lib/python3.7/site-packages/anndata/_core/anndata.py:1785: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  [AnnData(sparse.csr_matrix(a.shape), obs=a.obs) for a in all_adatas],
/cluster/home/hugifl/.local/lib/python3.7/site-packages/scanpy/tools/_tsne.py:115: UserWarning: In previous versions of scanpy, calling tsne with n_jobs > 1 would use MulticoreTSNE. Now this uses the scikit-learn version of TSNE by default. If you'd like the old behaviour (which is deprecated), pass 'use_fast_tsne=True'. Note, MulticoreTSNE is not actually faster anymore.
  "In previous versions of scanpy, calling tsne with n_jobs > 1 would use "
/cluster/home/hugifl/.local/lib/python3.7/site-packages/sklearn/manifold/_t_sne.py:783: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  FutureWarning,
Loaded checkpoint
Loaded from cache /cluster/scratch/hugifl/cytof_scRNA/1_init_cytof_codes.h5ad
Loaded from cache /cluster/scratch/hugifl/cytof_scRNA/1_init/evals.h5ad
Loaded checkpoint
Loaded checkpoint
Cache loading failed
Traceback (most recent call last):
  File "scRNA_cytof.py", line 357, in main
    evald = anndata.read(cache)
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 224, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/cluster/scratch/hugifl/cytof_scRNA/2_integrate_target/evals.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scRNA_cytof.py", line 377, in <module>
    main()
  File "scRNA_cytof.py", line 364, in main
    evald.write(cache)
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/anndata/_core/anndata.py", line 1924, in write_h5ad
    as_dense=as_dense,
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 75, in write_h5ad
    with h5py.File(filepath, mode) as f:
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/h5py/_hl/files.py", line 237, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 126, in h5py.h5f.create
FileNotFoundError: [Errno 2] Unable to create file (unable to open file: name = '/cluster/scratch/hugifl/cytof_scRNA/2_integrate_target/evals.h5ad', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
