python: can't open file 'coverage_data_prep_test.py': [Errno 2] No such file or directory
